/******************************************************************************/
/***          Generated by IBExpert 2008.08.19 19.05.2015 11:22:23          ***/
/******************************************************************************/

/*********
SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE '192.168.1.120:d:\program\nodejs__prjs\mixa_node_site_template2\routes\post\db\data_adminnax.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8;
************/


/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR t_word_ID;
SET GENERATOR t_word_ID TO 100;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE t_POST (
    ID_POST         VARCHAR(22),
    NAME            VARCHAR(1000) DEFAULT '',
    TAGS            VARCHAR(4000),
    TEXT            VARCHAR(8000),
    COMMENT_COUNT   INTEGER DEFAULT 0,
    VIZIT_COUNT     INTEGER DEFAULT 0,
    IS_MAIN         SMALLINT DEFAULT 0,
    IS_HIDDEN       SMALLINT DEFAULT 0,
    VOTING_PLUS     INTEGER,
    VOTING_MINUS    INTEGER,
    ID_USER_MODIFY  VARCHAR(22),
    ID_USER_CREATE  VARCHAR(22),
    DATE_MODIFY     TIMESTAMP DEFAULT current_timestamp,
    DATE_CREATE     TIMESTAMP
);


CREATE TABLE t_POST_TEXT (
    ID_POST  VARCHAR(22),
    N_ORDER  INTEGER,
    TEXT     VARCHAR(8000)
);


CREATE TABLE t_word__POST (
    ID_POST      VARCHAR(22) NOT NULL,
    ID_WORD      BIGINT NOT NULL,
    CNT          BIGINT NOT NULL,
    CREATE_DATE  TIMESTAMP
);


CREATE TABLE t_word (
    ID_WORD      BIGINT NOT NULL,
    WORD         VARCHAR(100) NOT NULL,
    CNT          BIGINT,
    CREATE_DATE  TIMESTAMP
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE UNIQUE INDEX IDX_t_POST_1 ON t_POST (ID_POST);
CREATE UNIQUE INDEX IDX_t_word_1 ON t_word (ID_WORD);
CREATE UNIQUE INDEX IDX_t_word_2 ON t_word (WORD);
CREATE INDEX IDX_t_word_3 ON t_word (CNT);
CREATE INDEX t_word__POST_IDX1 ON t_word__POST (ID_POST, CNT);
CREATE INDEX t_word__POST_IDX2 ON t_word__POST (ID_WORD, CNT);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: t_POST_BI0 */
CREATE TRIGGER t_POST_BI0 FOR t_POST
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  new.date_create = current_timestamp;
  new.date_modify = current_timestamp;

end
^


/* Trigger: t_POST_BU0 */
CREATE TRIGGER t_POST_BU0 FOR t_POST
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
    new.date_modify = current_timestamp;
end
^


/* Trigger: t_word_BI0 */
CREATE TRIGGER t_word_BI0 FOR t_word
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  new.create_date = current_timestamp;
end
^


/* Trigger: t_word__POST_BI0 */
CREATE TRIGGER t_word__POST_BI0 FOR t_word__POST
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  new.create_date = current_timestamp;
end
^


SET TERM ; ^

