SET SQL DIALECT 3;


CREATE TABLE TASK (
    IDC          CHAR(36),
    NAME         VARCHAR(500),
    NOTE         VARCHAR(2000),
    SCRIPT       VARCHAR(20000),
    CACHE_TEXT   VARCHAR(20000),
    CACHE_HASH   VARCHAR(40),
    DATE_CREATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_UPDATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE TASK_QUEUE (
    IDC          CHAR(36),
    USER_INFO    VARCHAR(5000),
    IDC_TASK     CHAR(36),
    DATE_CREATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_UPDATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_RUN     TIMESTAMP,
    DATE_END     TIMESTAMP
);



CREATE INDEX TASK_IDX1 ON TASK (CACHE_HASH);
CREATE UNIQUE INDEX TASK_IDX2 ON TASK (IDC);
CREATE UNIQUE INDEX TASK_QUEUE_IDX1 ON TASK_QUEUE (IDC);
CREATE INDEX TASK_QUEUE_IDX2 ON TASK_QUEUE (IDC_TASK);
